version: '3'
volumes:
  nfsmount:
      driver: local
      driver_opts:
          type: nfs
          o: addr=54.149.139.247
          device: ":/"
services:
  boxeradmin:
    build: .
    stdin_open: true
    tty: true
    command: /bin/bash
    volumes:
      - nfsmount:/efs
      - ~/.boxer:/root/.boxer
      - ~/.aws:/root/.aws
      - ~/.kube:/root/.kube
      - ~/.helm:/root/.helm
      - ~/.minikube:/root/.minikube
      - .:/boxeradmin

    
